version: '3'

services:
  pub:
    image: 'dockerhub.qingcloud.com/pressone/pub'
    command: bash -c "cd be && node bin/run"
    ports:
      - '8000:8000'
    volumes:
      - ./config/config.pub.js:/app/be/config.js:ro
      - ./config/config.pub-wallet.js:/app/be/config.wallet.js
    restart: 'always'
    depends_on:
      - postgres
      - redis

  pub-queue:
    image: 'dockerhub.qingcloud.com/pressone/pub'
    command: bash -c "cd be && yarn start-queue-prod"
    volumes:
      - ./config/config.pub.js:/app/be/config.js:ro
      - ./config/config.pub-wallet.js:/app/be/config.wallet.js
    restart: 'always'
    depends_on:
      - postgres
      - redis

  reader:
    image: 'dockerhub.qingcloud.com/pressone/reader'
    command: bash -c "cd be && wait-on -i 10000 http://pub:8000/api/ping && yarn start-prod"
    ports:
      - '9000:9000'
    volumes:
      - ./config/config.reader.js:/app/be/config.js:ro
      - ./config/config.reader-wallet.js:/app/be/config.wallet.js
    restart: 'always'
    depends_on:
      - postgres
      - redis

  reader-queue:
    image: 'dockerhub.qingcloud.com/pressone/reader'
    command: bash -c "cd be && wait-on -i 10000 http://pub:8000/api/ping && yarn start-queue-prod"
    volumes:
      - ./config/config.reader.js:/app/be/config.js:ro
      - ./config/config.reader-wallet.js:/app/be/config.wallet.js
    restart: 'always'
    depends_on:
      - postgres
      - redis
